services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: .deploy/nginx/nginx.prod.dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - default

  php:
    restart: always
    build:
      context: .
      dockerfile: .deploy/php/php.prod.Dockerfile
    depends_on:
      - pgsql
      - redis
    networks:
      - default
    env_file:
      - .env


  pgsql:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - "3000:8080"
    networks:
      - default

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - default

  certbot:
    restart: always
    build:
      context: .
      dockerfile: .deploy/certbot/Dockerfile
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    healthcheck:
      test: [ "CMD", "test", "-f", "/etc/letsencrypt/live/bot-reviewer.ru/fullchain.pem" ]
      interval: 1m
      retries: 5
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  database:
    driver: local
